[pytest]
# Основные настройки

# Опции командной строки по умолчанию
addopts = --alluredir=./target/allure-results

# Пути к тестам (по умолчанию ищет тесты в папке tests/)
testpaths = tests

# Шаблоны для поиска тестовых файлов, классов и функций
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Настройки для отчётов
junit_family = xunit2

# Настройки для покрытия кода (pytest-cov)
cov_report = term-missing
cov_source = my_project

# Настройки для Allure
allure_report_dir = ./target/allure-results